name: Alks-go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.7.x
          
    - name: Checkout code to GOPATH compatible directory
      uses: actions/checkout@v2
#       with:
#         fetch-depth: 1
#         path: go/src/github.com/Cox-Automotive/alks-go
  
    - name: Build
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        mkdir -p $GOPATH/src/github.com/$GITHUB_REPOSITORY
        mv $(pwd)/* $GOPATH/src/github.com/$GITHUB_REPOSITORY
        cd $GOPATH/src/github.com/$GITHUB_REPOSITORY

    - name: Debug
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
        echo ${PATH}
        go env
#       env:
#         GOPATH: /home/runner/work/alks-go/go

  
#     - name: Set GOPATH
#       run: export PATH=$PATH:$(go env GOPATH)/bin
        
    - name: Install additional dependencies
      run: |
        go get github.com/hashicorp/go-cleanhttp
        go get github.com/motain/gocheck
#        go test -cover $(go list ./... | grep -v /vendor/)
#       env:
#         GOPATH: /home/runner/work/alks-go/go

    - name: Test
      run: make test
